schemaVersion: 2.2.0
metadata:
  name: plain-devworkspace
attributes:
  devworkspace.org/started: "true"
components:
  - name: web-terminal
    container:
      image: docker.io/rohankanojia/base-developer-image:case1
      memoryRequest: 256Mi
      memoryLimit: 512Mi
      mountSources: true
      command:
        - tail
        - -f
        - /dev/null

