kind: DevWorkspace  
apiVersion: workspace.devfile.io/v1alpha2  
metadata:  
 name: plain-dw-with-home-vm  
spec:  
 started: true  
 routingClass: 'basic'  
 template:  
   components:  
     - name: pre-defined-home  
       volume: {}  
     - name: web-terminal  
       container:  
         image: quay.io/wto/web-terminal-tooling:next  
         memoryLimit: 512Mi  
         mountSources: true  
         volumeMounts:  
           - name: pre-defined-home  
             path: /home/user/  
         command:  
          - "tail"  
          - "-f"  
          - "/dev/null"
