apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  name: my-git-workspace
spec:
  started: true
  template:
    projects:
      - name: my-project
        git:
          remotes:
            origin: https://github.com/devfile-samples/devfile-sample-go-basic.git
    components:
      - name: tools
        container:
          image: quay.io/devfile/universal-developer-image:ubi8-latest
          command: ["/bin/sh"]
          args: ["-c", "while sleep 1000; do :; done"]
          mountSources: true

